# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestActivate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_activate(self):
    self.driver.get("http://localhost/travel%20ease/")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("benilbaisil001@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Admin1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-btn").click()
    self.driver.find_element(By.LINK_TEXT, "Packages").click()
    self.driver.find_element(By.CSS_SELECTOR, ".package-card:nth-child(2) .status-btn").click()
    self.driver.find_element(By.ID, "confirmButton").click()
  
