# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeactivate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.wait = WebDriverWait(self.driver, 10)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deactivate(self):
    self.driver.get("http://localhost/travel%20ease/")
    self.driver.set_window_size(1552, 880)
    
    # Login
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("User1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-btn").click()
    
    # Wait for login to complete and page to load
    time.sleep(2)
    
    # Scroll to enquiry section
    enquiry_section = self.driver.find_element(By.ID, "enquiry")
    self.driver.execute_script("arguments[0].scrollIntoView(true);", enquiry_section)
    time.sleep(1)
    
    # Fill enquiry form
    subject_input = self.wait.until(EC.presence_of_element_located((By.ID, "subject")))
    subject_input.click()
    subject_input.send_keys("Test Enquiry")
    
    message_input = self.driver.find_element(By.ID, "message")
    message_input.send_keys("This is a test enquiry message")
    
    # Submit the form
    submit_button = self.driver.find_element(By.CSS_SELECTOR, ".from-blue-600")
    submit_button.click()
    
    # Wait for success modal and close it
    time.sleep(2)
    ok_button = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".bg-green-600")))
    ok_button.click()
  
